#!/usr/bin/env python3
"""Every QuickJS global that is called must be registered, and vice versa.

`setQueueFifoTopN` shipped implemented, documented in
docs/how-to/matching-modes.md, and called from js_strategy.cpp -- while its
global was never registered. Every call was a ReferenceError. Nothing caught
it: the C++ compiles (the wrapper is a valid static function), the JS layer is
a string literal inside a C++ file, and no test called it.

Generating the registration table from flox_capi_spec.hpp is the obvious fix
and is not achievable as things stand: the global name is derivable (`__` plus
the C API function name) but the wrapper name is not --
`flox_simulated_executor_set_queue_model` is implemented by
`js_executor_set_queue_model`, and that correspondence lives nowhere. Wiring it
up would mean renaming all ~500 wrappers to a convention first.

So this checks the one thing the toolchain cannot: that every `__flox_*`
global the JS layer calls -- in the prelude and in the shipped quickjs/
examples -- has an addGlobalFunc registration. The call site is a string
inside a C++ string literal, invisible to the compiler, which is the whole
reason setQueueFifoTopN survived.

Two other checks were tried and dropped rather than shipped weak:

  - "every registration points at a defined wrapper" is already guaranteed by
    the compiler -- naming an undefined function in addGlobalFunc does not
    build. It also mis-fired on the ~40 wrappers generated by the
    STREAMING_FIELD / similar macros, which no definition regex sees.
  - "every global name maps to a C API function" mis-fired ~150 times: the
    `__` + name convention has real exceptions, e.g. `__flox_vprofile_create`
    wraps `flox_volume_profile_create`, abbreviated.

A gate people learn to ignore is worse than no gate.

Run:
    python3 scripts/check_quickjs_registration.py
    python3 scripts/check_quickjs_registration.py --verbose
"""

from __future__ import annotations

import argparse
import re
import sys
from pathlib import Path

REPO = Path(__file__).resolve().parent.parent
BINDINGS = REPO / "src" / "quickjs" / "js_bindings.cpp"
PRELUDE = REPO / "src" / "quickjs" / "js_strategy.cpp"
EXAMPLES = REPO / "quickjs"

# Globals that are defined by the prelude itself rather than by the C++ layer.
PRELUDE_PROVIDED: set[str] = set()

# Registered wrappers with no caller yet. Keep short and justified: an unused
# registration is dead weight, but it is not a bug the way a missing one is.
UNUSED_ALLOWLIST: dict[str, str] = {}


def registered_names() -> set[str]:
    """Every global name passed to addGlobalFunc.

    Only the string literal is extracted. An earlier version also captured the
    wrapper identifier, which silently missed the ~21 registrations that pass
    an inline lambda instead of a named function and reported all of them as
    unregistered. The name is the only part this gate needs.
    """
    text = BINDINGS.read_text(encoding="utf-8")
    return set(re.findall(r'addGlobalFunc\(\s*ctx\s*,\s*"([^"]+)"', text))


def called_globals(verbose: bool) -> dict[str, list[str]]:
    """global name -> where it is called from."""
    out: dict[str, list[str]] = {}
    sources = [PRELUDE]
    if EXAMPLES.is_dir():
        sources += sorted(EXAMPLES.rglob("*.js"))
    for src in sources:
        if not src.is_file():
            continue
        text = src.read_text(encoding="utf-8", errors="ignore")
        for name in set(re.findall(r'\b(__flox_\w+)\s*\(', text)):
            out.setdefault(name, []).append(str(src.relative_to(REPO)))
    if verbose:
        print(f"  scanned {len(sources)} JS source(s) for __flox_* calls")
    return out


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--verbose", action="store_true")
    args = ap.parse_args()

    for f in (BINDINGS, PRELUDE):
        if not f.is_file():
            print(f"error: {f} not found", file=sys.stderr)
            return 1

    regs = registered_names()
    calls = called_globals(args.verbose)

    print(f"QuickJS: {len(regs)} registrations, {len(calls)} globals called "
          f"from the JS layer.")

    problems: list[str] = []

    # 1. Called but never registered -- the setQueueFifoTopN shape.
    for name, where in sorted(calls.items()):
        if name in regs or name in PRELUDE_PROVIDED:
            continue
        problems.append(
            f"{name} is called from {', '.join(sorted(set(where)))} but has no "
            f"addGlobalFunc registration in js_bindings.cpp — every call is a "
            f"ReferenceError")

    # Informational: registered and defined, but nothing calls it.
    unused = sorted(set(regs) - set(calls) - set(UNUSED_ALLOWLIST))
    if unused and args.verbose:
        print(f"  {len(unused)} registration(s) with no caller in-tree "
              f"(not an error; the prelude is not the only consumer)")

    if problems:
        print("\nerror: QuickJS registration problems:\n", file=sys.stderr)
        for p in problems:
            print(f"  - {p}", file=sys.stderr)
        return 1

    print("OK: every global the JS layer calls is registered.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
