"""ABI snapshot — serialized representation of the C API surface.

Used by the CI gate to detect breaking changes: a snapshot file is
committed to `.api/c-api.snapshot`; CI re-derives a snapshot from the
current `flox_capi.h` and diffs against the committed file.

Format (text, deterministic, line-based):

    # ABI snapshot v1 — generated by tools/codegen/flox_codegen/abi_snapshot.py
    # name|return_type|param_type_1|param_type_2|...
    flox_indicator_ema|void|const double *|size_t|size_t|double *
    flox_strategy_create|FloxStrategyHandle|uint32_t|...
    ...

Functions are sorted by name; param types use libclang's canonical
spelling (so signed/unsigned width and const survive).

The snapshot intentionally covers free functions only — that's the
ABI break surface that 99% of FFI consumers care about. Struct field
layouts and enum values are NOT yet snapshotted (would be a v2).
"""
from __future__ import annotations

from dataclasses import dataclass
from pathlib import Path
from typing import Dict, Iterable, List

from . import check_signatures


SNAPSHOT_HEADER = "# ABI snapshot v1 — generated by tools/codegen/flox_codegen/abi_snapshot.py"
SNAPSHOT_FORMAT_DOC = "# name|return_type|param_type_1|param_type_2|..."


@dataclass(frozen=True)
class Diff:
    removed: List[str]
    added: List[str]
    changed: List[str]  # name only; details accumulated by reformat


def render(sigs: Dict[str, check_signatures.FuncSig]) -> str:
    """Serialize the snapshot deterministically."""
    out = [SNAPSHOT_HEADER, SNAPSHOT_FORMAT_DOC, ""]
    for name in sorted(sigs):
        sig = sigs[name]
        parts = [sig.name, sig.return_type, *sig.param_types]
        out.append("|".join(parts))
    return "\n".join(out) + "\n"


def parse(text: str) -> Dict[str, check_signatures.FuncSig]:
    """Parse a snapshot file back into FuncSig records."""
    out: Dict[str, check_signatures.FuncSig] = {}
    for line in text.splitlines():
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        parts = line.split("|")
        if len(parts) < 2:
            raise ValueError(f"malformed snapshot line: {line!r}")
        sig = check_signatures.FuncSig(
            name=parts[0],
            return_type=parts[1],
            param_types=tuple(parts[2:]),
        )
        out[sig.name] = sig
    return out


def from_header(path: Path, *, include_dirs: Iterable[Path] = ()) -> Dict[str, check_signatures.FuncSig]:
    """Build a snapshot dict from a C header by parsing it via libclang."""
    return check_signatures._index_header(path, include_dirs=include_dirs)


def diff(
    old: Dict[str, check_signatures.FuncSig],
    new: Dict[str, check_signatures.FuncSig],
) -> Diff:
    """Compute the breaking-change classifier for two snapshots.

    `removed` and `changed` are breaking. `added` is not.
    """
    removed = sorted(set(old) - set(new))
    added = sorted(set(new) - set(old))
    changed: List[str] = []
    for name in sorted(set(old) & set(new)):
        if old[name] != new[name]:
            changed.append(name)
    return Diff(removed=removed, added=added, changed=changed)


def is_breaking(d: Diff) -> bool:
    """A diff is breaking when an existing symbol disappeared or changed shape."""
    return bool(d.removed or d.changed)
